# DataForge AI — developer task runner.
# Backend targets run from ./backend; frontend targets from ./frontend.

.DEFAULT_GOAL := help
BACKEND := backend
FRONTEND := frontend

.PHONY: help
help: ## Show available targets
	@grep -hE '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-22s\033[0m %s\n", $$1, $$2}'

# --- Environment -----------------------------------------------------------
.PHONY: install
install: ## Install backend and frontend dependencies
	cd $(BACKEND) && pip install -r requirements.txt -r requirements-dev.txt
	cd $(FRONTEND) && npm ci

# --- Backend ---------------------------------------------------------------
.PHONY: migrate
migrate: ## Apply database migrations (alembic upgrade head)
	cd $(BACKEND) && alembic upgrade head

.PHONY: revision
revision: ## Create a new autogenerated migration (msg="...")
	cd $(BACKEND) && alembic revision --autogenerate -m "$(msg)"

.PHONY: run
run: ## Run the API server with autoreload
	cd $(BACKEND) && uvicorn src.main:app --reload --port 8000

.PHONY: worker
worker: ## Run a Celery worker (all queues)
	cd $(BACKEND) && celery -A src.celery_app worker --loglevel=info \
		-Q default,high_priority,heavy_ops

.PHONY: test
test: ## Run backend tests with coverage
	cd $(BACKEND) && python -m pytest --cov=src --cov-config=.coveragerc \
		--cov-report=term-missing tests/

.PHONY: lint
lint: ## Lint backend (ruff) and frontend (eslint)
	cd $(BACKEND) && ruff check src
	cd $(FRONTEND) && npm run lint

.PHONY: fmt
fmt: ## Auto-format backend (ruff) code
	cd $(BACKEND) && ruff format src tests

.PHONY: typecheck
typecheck: ## Static type check the backend (mypy)
	cd $(BACKEND) && mypy src

# --- Docker ----------------------------------------------------------------
.PHONY: up
up: ## Build and start the full stack
	docker compose up --build -d

.PHONY: down
down: ## Stop the stack
	docker compose down

.PHONY: logs
logs: ## Tail backend logs
	docker compose logs -f backend
