[mypy]
plugins = sqlalchemy.ext.mypy.plugin
ignore_missing_imports = True

[mypy-src.auth.models]
disable_error_code = assignment

[mypy-src.datasets.models]
disable_error_code = assignment

[mypy-src.pipelines.models]
disable_error_code = assignment

[mypy-src.monitoring.models]
disable_error_code = assignment
